### ISSUE TITLE
ошибка оплаты услуг

### ISSUE THREAD

**Issue by CookLand** [evgeny-tc/dle-billing-module#16]
начал тестировать .
в начале начал теситровать платную фиксацию и ничего не работает . 

Нашел на старых сайтах инфу о том что сразу после установки нужно сделать:

В шаблоне необходимо подключить CSS и JS файлы.
<link href="{THEME}/billing/css/styles.css" type="text/css" rel="stylesheet">

<script src="{THEME}/billing/js/scripts.js"></script>
<script src="{THEME}/billing/js/fixednews.js"></script>
<script src="{THEME}/billing/js/helpers.js"></script>
<script src="{THEME}/billing/js/paygroups.js"></script>

Далее включил модуль. и как с полной новости перехожу по ссылке billing.html/pay/waiting/id/4 чтобы оплатить заказ то 500 ошибка прилетает, но вот когда непосредственно переходишь в Кабинет пользователя /billing.html и нажимая пополнить по кнопке то страница billing.html/pay/waiting/id/5 уже доступна и работает .

в чем может быть проблема когда перехожу из всплывающего окна ?
может кто то сталкивался с таким багом . тестирую на чистой DLE 14.3 и PHP 7.4

оплата услуги тип : пополнение баланса получается работает .
но вот когда квитанция оплата услуг не работает белый экран и 500 ошибка ..

где копать по этой ошибке?

**Comment by evgeny-tc** [comment]
>В шаблоне необходимо подключить CSS и JS файлы.

спасибо, добавил в инструкцию

>может кто то сталкивался с таким багом . тестирую на чистой DLE 14.3 и PHP 7.4

php нужен версии 8 и выше

**Comment by CookLand** [comment]
> > В шаблоне необходимо подключить CSS и JS файлы.
> 
> спасибо, добавил в инструкцию
> 
> > может кто то сталкивался с таким багом . тестирую на чистой DLE 14.3 и PHP 7.4
> 
> php нужен версии 8 и выше

эх на php 8 и выше пока не могу перевести так как другие модули и плагины адаптированы на php 7.4 и при выключении 8.1 они отваливаются..  но а так для теста сделаю отдельный тестовый и отпишусь . спасибо за оперативность.

**Comment by evgeny-tc** [comment]
Версии 0.7.*

**Comment by CookLand** [comment]
поставил DLE 16.1 и PHP 8.1 установка прошла успешно. 

для DLE 16.1 подключать CSS и JS теперь можно и так:

```
{include file="{THEME}/billing/css/styles.css"}
```

```
{include file="{THEME}/billing/js/scripts.js"}
{include file="{THEME}/billing/js/fixednews.js"}
{include file="{THEME}/billing/js/helpers.js"}
{include file="{THEME}/billing/js/paygroups.js"}
```


далее зайдя в раздел Плагины => Платная фиксация новостей  открылось окно настройки...
и поставив галочку на Включить и если разделы Закрыть группы: и Закрыть категории: не выбрать ничего ( тоесть оставить поле пустым то выскакивает ошибка : 

```
Fatal error: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /public_html/domen/anime/engine/modules/billing/plugins/fixednews/adm.main.php:31 
Stack trace: #0 /public_html/domen/anime/engine/modules/billing/plugins/fixednews/adm.main.php(31): implode() #1 /public_html/domen/anime/engine/modules/billing/helpers/dashboard.php(189): ADMIN->main() #2 /public_html/domen/anime/engine/modules/billing/helpers/dashboard.php(31): Dashboard->Loader() #3 /public_html/domen/anime/engine/modules/billing/admin.php(51): Dashboard::Start() #4 /public_html/domen/anime/engine/inc/billing.php(16): require_once('/home/...') #5 /public_html/domen/anime/engine/inc/include/init.php(587): include_once('/home/...') #6 /public_html/domen/anime/admin.php(29): require_once('/home/...') #7 {main} thrown in /public_html/domen/anime/engine/modules/billing/plugins/fixednews/adm.main.php on line 31 
```

но если выбрать какой нибудь параметр и одну категорию  то сохранение происходит нормально .
